name: magic_tales
description: "Create magic tales together"

publish_to: none

environment:
  sdk: ^3.2.0

dependencies:
  cupertino_icons: ^1.0.6
  firebase_core: ^3.3.0
  firebase_vertexai: ^0.2.2+4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.3
  google_generative_ai: ^0.4.3
  intl: any

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
  generate: true #useful for the localization
