// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrfm0s_QsgPaKlc4Ik9Lw_JN2iKDgmatY',
    appId: '1:976740893005:web:f419db773d27ed98d87704',
    messagingSenderId: '976740893005',
    projectId: 'magic-tales-90a32',
    authDomain: 'magic-tales-90a32.firebaseapp.com',
    storageBucket: 'magic-tales-90a32.appspot.com',
    measurementId: 'G-YS0LRH8Z8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7IUGedvcC0s5Hr8i23Ulfx752M2ETZeU',
    appId: '1:976740893005:android:bb68c0465538c166d87704',
    messagingSenderId: '976740893005',
    projectId: 'magic-tales-90a32',
    storageBucket: 'magic-tales-90a32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK9RHyxDcFYtZ_rU6b_q4nKMq4ONvGa0I',
    appId: '1:976740893005:ios:bd03d0cdf9fb5995d87704',
    messagingSenderId: '976740893005',
    projectId: 'magic-tales-90a32',
    storageBucket: 'magic-tales-90a32.appspot.com',
    iosBundleId: 'com.example.magicTales',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK9RHyxDcFYtZ_rU6b_q4nKMq4ONvGa0I',
    appId: '1:976740893005:ios:bd03d0cdf9fb5995d87704',
    messagingSenderId: '976740893005',
    projectId: 'magic-tales-90a32',
    storageBucket: 'magic-tales-90a32.appspot.com',
    iosBundleId: 'com.example.magicTales',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrfm0s_QsgPaKlc4Ik9Lw_JN2iKDgmatY',
    appId: '1:976740893005:web:0227a8956bfafcd1d87704',
    messagingSenderId: '976740893005',
    projectId: 'magic-tales-90a32',
    authDomain: 'magic-tales-90a32.firebaseapp.com',
    storageBucket: 'magic-tales-90a32.appspot.com',
    measurementId: 'G-7PVYJ90YMZ',
  );
}
